{
 "title": "Vast Dashboard",
 "tags": [ "Prometheuse" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "CPU_Max_Power", "label": "CPU Max Power", "query": "300" },
   { "name": "BasePower", "label": "BasePower", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Pending Payout",
   "type": "stat",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vastai_current_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Income per hour",
   "type": "stat",
   "description": "Based on incress of the pending balance over the laste hour",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deriv(vastai_current_total[1h]) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reported Income per day",
   "type": "stat",
   "description": "Reported by vast for all machines",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_earn_hour)/1.25",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines Listed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_machine_Listed)/ sum(vast_machine_hostname) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines verfied",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_machine_Verification)/ sum(vast_machine_hostname) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vast_machine_hostname)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Toal GPU's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vast_machine_gpu_name)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Actual vs Vast registred",
   "type": "gauge",
   "description": "This shows how many of the GPUs are detected by the systems vs what each machine has registered on vast. ",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{})/sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Used On-demand",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_rented_on_demand) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Used Bid",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_rented_bid_demand) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU's Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_idle) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine_Info",
   "type": "table",
   "description": "As reported by vast api.",
   "gridPos": { "h": 30, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "vast_machine_gpu_name", "legendFormat": "__auto" },
    { "expr": "vast_machine_hostname", "legendFormat": "__auto" },
    {
     "expr": "vastai_machine_current_rentals_resident",
     "legendFormat": "__auto"
    },
    { "expr": "vastai_machine_gpu_idle", "legendFormat": "__auto" },
    {
     "expr": "vastai_machine_gpu_rented_bid_demand",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_rented_on_demand",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_avail_disk_space",
     "legendFormat": "__auto"
    },
    { "expr": "vast_machine_Listed", "legendFormat": "__auto" },
    { "expr": "vast_machine_Verification", "legendFormat": "__auto" },
    { "expr": "vast_machine_Reliability", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reported GPU Count",
   "type": "table",
   "gridPos": { "h": 30, "w": 3, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_FB_USED) by (Hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Reliability",
   "type": "timeseries",
   "description": "As reported by vast api.",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (vast_machine_Reliability) by (machine_id)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Current Machine earnings per day",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(vastai_machine_earn_hour)  by (machine_id)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine Online Status",
   "type": "state-timeline",
   "description": "As reported by vast api.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(machine_id) (vast_machine_timeout)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine Error Status",
   "type": "state-timeline",
   "description": "As reported by vast api.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by(machine_id) (vastai_machine_ErrorDescription)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machines Power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "$CPU_Max_Power * count by (job)(node_cpu_temperature{package=~\"[0-9]+\"})/2 + sum by (job) (DCGM_FI_DEV_POWER_USAGE) + $BasePower +$CPU_Max_Power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine usage On-demand",
   "type": "timeseries",
   "description": "Avraged over 24h as reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum(vastai_machine_gpu_rented_on_demand) by (machine_id) / \r\n    sum(vast_machine_gpu_name) by (machine_id)\r\n  )[2h:1m]\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Core Hot Spot",
   "type": "table",
   "gridPos": { "h": 35, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Core Hot Spot",
   "type": "table",
   "gridPos": { "h": 35, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Temps",
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU FAN Speeds",
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Power",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU VRAM Temps ",
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Thermal Throttle",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU AER_ RRORS",
   "type": "table",
   "description": "AER  Advanced Error Reporting by PCI Express devices",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Error State",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "GPU_ERROR_STATE{ gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{ gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{ gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"7\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"8\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"9\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"10\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{ gpu=\"11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{ gpu=\"12\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Internet Down speed",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(machine_id) (vast_machine_InetDown)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine avail disk space reported by vast",
   "type": "timeseries",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(sum(vastai_machine_avail_disk_space)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings Bandwith  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_bwd_earn+vastai_per_machine_bwu_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings storage  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_sto_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine Internet Upload speed",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(machine_id) (vastai_machine_InetUp)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings for GPUs  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_gpu_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_gpu_earn+vastai_per_machine_bwd_earn+vastai_per_machine_bwu_earn+vastai_per_machine_sto_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  }
 ]
}