version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "80:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./cpu_power_usage_rules.yml:/etc/prometheus/cpu_power_usage_rules.yml
      - prometheus-data:/prometheus
    restart: always

  node-exporter:
    image: jjziets/my-node-exporter:latest
    container_name: my-node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    hostname: "vastbackup"
    volumes:
      - "/:/host:ro,rslave"
    command: ["--path.rootfs=/host"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"

  vastai-exporter:
    image: jjziets/vastai-exporter
    ports:
      - "8622:8622"
    command:
      - "--api-key=your_vast_api_key" //Remeber to chagne this 
    restart: always

  dcgm-exporter:
    image: jjziets/dcgm-exporter:latest
    container_name: dcgm-exporter
    restart: unless-stopped
    ports:
      - "9400:9400"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    hostname: "vastbackup"


    
volumes:
  grafana-data:
  prometheus-data:
